version: '3.4'
services:
  mariadb:
    image: mysql:8.0 # mariadb:11.5.2
    ports:
    - "3306:3306"
    command:
      --int-file /data/application/init.sql
    environment:
      MYSQL_ROOT_USER: javafxTest
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: javafxTest
      MYSQL_USER: javafxTest
      MYSQL_PASSWORD: changeme
    volumes:
      - ${PWD}/mariadb:/var/lid/mysql
      - ./int.sql:/data/application/init.sql
    network_mode: "host"